apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "image-optimize-proxy.fullname" . }}
  labels:
    {{- include "image-optimize-proxy.labels" . | nindent 4 }}
data:
  LISTEN_ADDR: {{ .Values.config.listenAddr | quote }}
  IMGPROXY_URL: {{ .Values.config.imgproxyUrl | quote }}
  CACHE_S3_BUCKET: {{ .Values.config.cacheS3Bucket | quote }}
  CACHE_S3_REGION: {{ .Values.config.cacheS3Region | quote }}
  MAX_WIDTH: {{ .Values.config.maxWidth | quote }}
  UPSTREAM_TIMEOUT: {{ .Values.config.upstreamTimeout | quote }}
  IMGPROXY_TIMEOUT: {{ .Values.config.imgproxyTimeout | quote }}
  SHUTDOWN_TIMEOUT: {{ .Values.config.shutdownTimeout | quote }}
  ASYNC_CACHE_PUT_CONCURRENCY: {{ .Values.config.asyncCachePutConcurrency | quote }}
  ASYNC_CACHE_PUT_TIMEOUT_SECONDS: {{ .Values.config.asyncCachePutTimeoutSeconds | quote }}
  {{- if .Values.config.allowedUpstreamGateways }}
  ALLOWED_UPSTREAM_GATEWAYS: {{ .Values.config.allowedUpstreamGateways | quote }}
  {{- end }}
  {{- if .Values.config.allowedSourceBuckets }}
  ALLOWED_SOURCE_BUCKETS: {{ .Values.config.allowedSourceBuckets | quote }}
  {{- end }}
  DEFAULT_QUALITY: {{ .Values.config.defaultQuality | quote }}
