{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "image-optimize-proxy.fullname" . }}
  labels:
    {{- include "image-optimize-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "image-optimize-proxy.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}
  {{- end }}
{{- end }}
